name: school-menu-connector
services:
- name: web
  github:
    repo: asachs01/school_menu_connector
    branch: main
  dockerfile_path: Dockerfile
  run_command: ./main
  routes:
  - path: /
  - path: /get-menu